default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
popon: styles/popon.scss
popon-sakura: styles/popon-sakura.scss
popon-sakura-new: styles/popon-sakura-new.scss
